[package]
name = "ton_sdk"
version = "0.1.0"

[dependencies]
rand = "0.6.1"
pretty_assertions = "0.5.1"
num-bigint = "0.2.2"
sha2 = "^0.7"
reql = "^0.0.26"
#reql-macros = "^0.0.19"
reql-types = "^0.0.4"
futures = "^0.1.26"
serde_json = "^1.0.39"
serde = "^1.0.90"
serde_derive = "^1.0.90"
error-chain = { version = "^0.12", default-features = false }
hex = "0.3.2"
ed25519-dalek = "^0.8"
#rdkafka = "0.20.0"
tokio = "0.1.18"
lazy_static = "1.1.0"
base64 = "0.10.0"

abi-lib =  { path = "abi/static" }
abi-lib-dynamic = { git = "ssh://git@github.com/tonlabs/TON-SDK.git", branch = "temp-dynamic-abi-other-dependecny", package = "abi-lib-dynamic" }

tvm = { git = "ssh://git@github.com/tonlabs/sdk-emulator.git", branch = "feature-blockchain-structs-to-jsons", package = "tvm" }
ton_block = { git = "ssh://git@github.com/tonlabs/sdk-emulator.git", branch = "feature-blockchain-structs-to-jsons", package = "ton_block" }

#[dev-dependencies.compiletest_rs]
#features = ["tmp", "stable"]
#version = "*"

[features]
ci_run = []

[dependencies.kafka]
version = "0.7"
default-features = false