[package]
name = "tonos_client_react_native_ios"
version = "1.1.0"
authors = ["TON Labs"]
license = "Apache-2.0"

[lib]
name = "tonosclient"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
ton_client = { path = "../../../client" }

[profile.release]
lto = true
