[package]
name = "ton_client"
version = "0.9.50"
authors = ["Michael Vlasov"]
rpath = true

[lib]
name = "tonclient"
crate-type = ["cdylib"]

[dependencies]
rand = "0.6.1"
hex = "0.3.2"
serde_json = "1.0.39"
serde_derive = "1.0.91"
serde = "1.0.91"
ed25519-dalek = "^0.9.1"
sha2 = "^0.8"
futures = "^0.1.26"
base64 = "0.10.0"
reql-types = "^0.0.4"
lazy_static = "1.1.0"
num-bigint = "0.2.2"
sodalite = { version = "0.3.0", features = ["rand"] }
chrono = "0.4.6"
scrypt = { version = "0.2.0", default-features = false }
bip39 = { git = "https://github.com/tonlabs/bip39-rs.git" }
hmac = "0.7.1"
base58 = "0.1.0"
pbkdf2 = { version = "0.3.0", default-features = false, features = [] }
byteorder = "1.3.2"
libsecp256k1 = "0.2.2"
log = "0.4.6"

ton_sdk = { path = "../ton_sdk", features = ["node_interaction"] }

[dependencies.tvm]
git = "ssh://git@github.com/tonlabs/sdk-emulator.git"
branch = "feature-dev"
package = "tvm"
default-features = false

