[package]
name = "ton_client"
version = "0.9.50"
authors = ["Michael Vlasov"]

[lib]
name = "tonclient"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.1.0"
serde_json = "1.0.40"
serde = "1.0.99"

ton_sdk = { path = "../ton_sdk" }


[features]
