[package]
name = "api_doc_derive"
version = "0.1.0"
authors = ["Michael Vlasov <melsomino@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
api_doc = { path = "../api_doc" }

