[package]
name = "graphite"
version = "0.1.0"
edition = "2018"

[lib]
name = "graphite"
crate-type = ["rlib"]

[dependencies]
tokio-tungstenite = "0.11.0"
serde_json = "1.0.41"
reqwest = "0.10.4"
failure = "0.1"
futures = "0.3.4"
