[package]
name = "ton_client_node_js"
version = "0.10.0"
authors = ["Michael Vlasov"]

[lib]
name = "ton_client_node_js"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
ton_client = { path = "../../client" }

[profile.release]
lto = true

