[package]
name = "abi-lib"
version = "0.1.0"


[dependencies]
tvm = { path = "../../tvm" }
rust-crypto = "^0.2"
num-bigint = "0.2.2"

[dev-dependencies.compiletest_rs]
features = ["tmp", "stable"]
version = "*"
