[package]
name = "ton_sdk"
version = "0.1.0"

[dependencies]
rand = "0.6.1"
pretty_assertions = "0.5.1"
num-bigint = "0.2.2"
sha2 = "0.8"
serde_json = "1.0.41"
serde = "1.0.91"
serde_derive = "1.0.91"
error-chain = { version = "^0.12", default-features = false }
hex = "0.3.2"
ed25519-dalek = "^0.9.1"
lazy_static = "1.1.0"
base64 = "0.10.0"
crc16 = "0.4.0"
chrono = "0.4.9"

ton_abi = { path = "../ton_abi" }


[target.'cfg(target_arch="wasm32")'.dependencies]
rand = { version = "0.6.1", features = ["wasm-bindgen"] }
chrono = { version = "0.4.9", features = ["wasmbind"] }


[dependencies.tvm]
git = "ssh://git@github.com/tonlabs/sdk-emulator.git"
branch = "0.16.0-rc"
package = "tvm"
default-features = false

[dependencies.futures]
version = "^0.1.26"
optional = true

[dependencies.graphite]
path = "../graphite"
optional = true

[dependencies.reqwest]
version = "0.9.18"
features = ["default-tls-vendored"]
optional = true

[features]
default = ["node_interaction"]
ci_run = []
node_interaction = ["graphite", "futures", "reqwest"]

