[package]
name = "tonclientreactnative"
version = "0.9.50"
authors = ["Michael Vlasov"]

[lib]
name = "tonclientreactnative"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
jni = { version = "0.12.0", optional = true, default-features = false }
ton_client = { path = "../../../client" }

[features]
default = ["jni"]

[profile.release]
lto = true
